### ISSUE TITLE
Shunting Jobs

### ISSUE THREAD

**Issue by SomeGuy159753** [fauxnik/DVOwnership#76]
**1. Shunt Load Jobs**
Would it be at all possible for shunt load  jobs to have the destination track match the loading track, like the persistent jobs mod does?
That way as soon as you have hit load you can hand in the job and then store the cars as you want or add them to a train you are building for a haul.

**2. Shunt Unload Jobs**
Would the above work for unload jobs? Once you unload and hand in the job it generates a load job containing one or more of the cars you just unloaded as well as other eligible empties in the yard, this would require shunting but it wouldn't feel like unnecessary work. 

Alternatively, have the unload jobs work the same way as persistent jobs as well, where after unload you store in specified locations and then load jobs are assigned to those cars on your next visit to that particular station. I know this may hinder early game play a bit, i Haven't been able to figure out a way to get around that. 

I think implementing one or both of the above could help mitigate the feeling of doing unnecessary work in the yard, once a job is loaded you can immediately add it to a train being built for a haul or store it for later. When unloading you can either store the cars as you need in favor of another job or do some shunting to build the next cut to be loaded.

**Comment by fauxnik** [comment]
I was the one who added this gameplay change to Persistent Jobs. While it was very convenient, it caused so many players confusion that it lead to me abandoning Persistent Jobs and starting Rolling Stock Ownership with the promise not to change the way the game handles jobs so significantly.

The only way that you will get this is if someone develops a companion mod that introduces this functionality.

**Comment by SomeGuy159753** [comment]
oh okay, I understand.

**Comment by matejdro** [comment]
Maybe this could be added as an opt-in to the Mod manager settings?

It is very annoying to have to move the wagons to the random track, just to have them move again a moment after for a freight job. Especially if the game wants you to split the train into multiple tracks (requiring you to merge it right back after the job is handed in).
